---
name: Build and Push - Github Container Registry

on:
  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      context:
        description: 'The context to use for the Docker build (default: current directory)'
        required: false
        default: .
        type: string
      dockerfilePath:
        description: 'The path to the Dockerfile to use for the build (default: Dockerfile)'
        required: false
        default: Dockerfile
        type: string
    secrets:
      buildArgs:
        description: Build arguments to pass to the Docker build command (optional). Do *not* include the --build-arg flag in the value. Multiple build arguments can be passed by separating them with spaces.
        required: false

jobs:
  build:
    name: Build and Push - Github Container Registry
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    defaults:
      run:
        shell: bash

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

    - name: Log in to the Container registry
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw, enable=true, value=${{ github.run_id }}, priority=1000
          type=raw, enable=true, value=${{ github.sha }}, priority=900
          type=ref,event=branch

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfilePath }}
        build-args: ${{ secrets.buildArgs }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
